"""Adiciona log_retorno a tabela Agenda

Revision ID: 14300b946cff
Revises: 1791cbc1a646
Create Date: 2026-01-27 15:41:41.452839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14300b946cff'
down_revision = '1791cbc1a646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agenda', schema=None) as batch_op:
        batch_op.alter_column('fertipar_embalagem',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agenda', schema=None) as batch_op:
        batch_op.alter_column('fertipar_embalagem',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=60),
               existing_nullable=True)

    # ### end Alembic commands ###
