"""Cria a tabela LogErro para registro de falhas

Revision ID: 2d60a5a0872f
Revises: 14300b946cff
Create Date: 2026-02-02 14:55:20.371913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d60a5a0872f'
down_revision = '14300b946cff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_erro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('agenda_id', sa.Integer(), nullable=True),
    sa.Column('route', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('screenshot_path', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['agenda_id'], ['agenda.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agenda', schema=None) as batch_op:
        batch_op.alter_column('cam_erro_img',
               existing_type=sa.VARCHAR(length=400),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agenda', schema=None) as batch_op:
        batch_op.alter_column('cam_erro_img',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=400),
               existing_nullable=True)

    op.drop_table('log_erro')
    # ### end Alembic commands ###
