"""Adjust password_hash length and add nullable fields to configuracao_robo

Revision ID: 3c07e071d17b
Revises: 60d7e36948ff
Create Date: 2026-01-15 01:46:44.174556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c07e071d17b'
down_revision = '60d7e36948ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cargas_executada', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_cargas_executada_caminhao_id'))
        batch_op.drop_index(batch_op.f('idx_cargas_executada_motorista_id'))

    op.drop_table('cargas_executada')
    with op.batch_alter_table('agenda', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_agenda_caminhao_id'))
        batch_op.drop_index(batch_op.f('idx_agenda_motorista_id'))
        batch_op.drop_index(batch_op.f('idx_agenda_status'))
        batch_op.create_unique_constraint(None, ['fertipar_protocolo'])

    with op.batch_alter_table('configuracao_robo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senha_site_hash', sa.String(length=128), nullable=True))
        batch_op.alter_column('tempo_espera_segundos',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('30'))
        batch_op.drop_column('senha_site')
        batch_op.drop_column('senha_site_encrypted')

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)

    with op.batch_alter_table('configuracao_robo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senha_site_encrypted', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('senha_site', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.alter_column('tempo_espera_segundos',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('30'))
        batch_op.drop_column('senha_site_hash')

    with op.batch_alter_table('agenda', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('idx_agenda_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_agenda_motorista_id'), ['motorista_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_agenda_caminhao_id'), ['caminhao_id'], unique=False)

    op.create_table('cargas_executada',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('data', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('caminhao_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('motorista_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['caminhao_id'], ['caminhao.id'], name=op.f('cargas_executada_caminhao_id_fkey')),
    sa.ForeignKeyConstraint(['motorista_id'], ['motorista.id'], name=op.f('cargas_executada_motorista_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('cargas_executada_pkey'))
    )
    with op.batch_alter_table('cargas_executada', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_cargas_executada_motorista_id'), ['motorista_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_cargas_executada_caminhao_id'), ['caminhao_id'], unique=False)

    # ### end Alembic commands ###
