"""Initial migration for PostgreSQL

Revision ID: 60d7e36948ff
Revises: 
Create Date: 2026-01-10 16:01:12.628825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60d7e36948ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caminhao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=10), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('tipo_carroceria', sa.String(length=50), nullable=True),
    sa.Column('placa_reboque1', sa.String(length=10), nullable=True),
    sa.Column('uf1', sa.String(length=2), nullable=True),
    sa.Column('placa_reboque2', sa.String(length=10), nullable=True),
    sa.Column('uf2', sa.String(length=2), nullable=True),
    sa.Column('placa_reboque3', sa.String(length=10), nullable=True),
    sa.Column('uf3', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('placa')
    )
    op.create_table('configuracao_robo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_acesso', sa.String(length=255), nullable=False),
    sa.Column('filial', sa.String(length=50), nullable=False),
    sa.Column('usuario_site', sa.String(length=80), nullable=False),
    sa.Column('senha_site', sa.String(length=80), nullable=False),
    sa.Column('email_retorno', sa.String(length=100), nullable=False),
    sa.Column('pagina_raspagem', sa.String(length=255), nullable=True),
    sa.Column('contato', sa.String(length=100), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('head_evento', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('motorista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=20), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.String(length=200), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telefone_fixo', sa.String(length=20), nullable=True),
    sa.Column('celular', sa.String(length=20), nullable=True),
    sa.Column('foto_perfil', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('agenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('motorista_id', sa.Integer(), nullable=False),
    sa.Column('caminhao_id', sa.Integer(), nullable=False),
    sa.Column('fertipar_protocolo', sa.String(length=100), nullable=False),
    sa.Column('fertipar_pedido', sa.String(length=100), nullable=True),
    sa.Column('fertipar_destino', sa.String(length=100), nullable=True),
    sa.Column('fertipar_data', sa.String(length=50), nullable=True),
    sa.Column('fertipar_qtde', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('data_agendamento', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['caminhao_id'], ['caminhao.id'], ),
    sa.ForeignKeyConstraint(['motorista_id'], ['motorista.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fertipar_protocolo')
    )
    op.create_table('cargas_executada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('data', sa.String(length=20), nullable=False),
    sa.Column('caminhao_id', sa.Integer(), nullable=True),
    sa.Column('motorista_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['caminhao_id'], ['caminhao.id'], ),
    sa.ForeignKeyConstraint(['motorista_id'], ['motorista.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cargas_executada')
    op.drop_table('agenda')
    op.drop_table('usuario')
    op.drop_table('motorista')
    op.drop_table('configuracao_robo')
    op.drop_table('caminhao')
    # ### end Alembic commands ###
