"""Altera o armazenamento da senha do robô para um formato criptografado reversível e corrige a lógica de scraping.

Revision ID: fd23e71f47d4
Revises: 3c07e071d17b
Create Date: 2026-01-15 09:52:54.165855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd23e71f47d4'
down_revision = '3c07e071d17b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracao_robo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senha_site_encrypted', sa.String(length=255), nullable=True))
        batch_op.drop_column('senha_site_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracao_robo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senha_site_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
        batch_op.drop_column('senha_site_encrypted')

    # ### end Alembic commands ###
